name: Run tests on supported Python versions

on: [push, pull_request, workflow_dispatch]

jobs:
    extensive_tests:
        name: Run tests on Python ${{ matrix.python }}
        runs-on: ${{ matrix.os }}
        defaults:
          run:
            shell: bash
        strategy:
            fail-fast: false
            matrix:
                python: ["3.10", "3.11", "3.12", "3.13", "3.14"]
                os: ["ubuntu-latest"]

        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
              with:
                persist-credentials: false

            - name: Set up Python
              uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
              with:
                python-version: "${{ matrix.python }}"

            - name: Run tests
              run: make clean && make dev && make test
